### ISSUE TITLE
ESP32 error: 'constexpr' needed

### ISSUE THREAD

**Issue by MacrossGalang** [GiorgosXou/NeuralNetworks#17]
Hello Sir
I found this error in "any activation function per layer" example when compiling in esp32
however if I compile it using arduino uno it was just working fine

I have try to remove the "const" from the line, but still problem

C:\Users\macro\Documents\Arduino\libraries\NeuralNetwork\src/NeuralNetwork.h:444:9: error: 'activation_Function_ptrs' declared as an 'inline' field
         };
         ^
C:\Users\macro\Documents\Arduino\libraries\NeuralNetwork\src/NeuralNetwork.h:444:9: error: 'constexpr' needed for in-class initialization of static data member 'float (NeuralNetwork::Layer::* const NeuralNetwork::activation_Function_ptrs [2])(const float&)' of non-integral type [-fpermissive]

C:\Users\macro\Documents\Arduino\libraries\NeuralNetwork\src/NeuralNetwork.h:471:13: error: 'derivative_Function_ptrs' declared as an 'inline' field
             };
             ^
C:\Users\macro\Documents\Arduino\libraries\NeuralNetwork\src/NeuralNetwork.h:471:13: error: 'constexpr' needed for in-class initialization of static data member 'float (NeuralNetwork::Layer::* const NeuralNetwork::derivative_Function_ptrs [2])(const float&)' of non-integral type [-fpermissive]

**Comment by GiorgosXou** [comment]
Hello @MacrossGalang, I tried both of the available board-packages and it compile just fine, I'm not sure how to reproduce your issue, could you add more informations about how you compile it and which exactly one esp32 you use?

![image](https://github.com/GiorgosXou/NeuralNetworks/assets/11987271/f063e740-66bd-49e5-b6f4-bca1b23f9aa1)

**Comment by MacrossGalang** [comment]
Hello Sir
the problem solve Sir
I just need to update the esp32 board-packages
from 2.0.8 to become 2.0.11 just like your screenshot above
thank you Sir
