### ISSUE TITLE
Multiple outputs

### ISSUE THREAD

**Issue by lewisrichardson2103** [GiorgosXou/NeuralNetworks#4]
Hello,

I have tried using this with multiple outputs but the error does not reduce. 

I have a network with 6 inputs, 1 hidden layer (7 nodes) and output layer of 3 outputs(a,b,c). When trying to teach the network there is no change to the error over time. When I use the same network but reduce the output to 1 node (replace with 0=a, 0.5 =b and 1 =c) then it works and the error is reduced over time.

Do you know why this would be? I believe the backpropagation does not work correctly with multiple outputs.

thank you

Lewis

**Comment by GiorgosXou** [comment]
**Hello** Lewis,

> I have tried using this with multiple outputs but the error does not reduce.

**You are right**, thanks you so much for pointing this issue out, i wasn't aware of it.
now it is fixed, you can change the file of the library or just the line and you will be fine, here it is the [fix](https://github.com/GiorgosXou/NeuralNetworks/commit/44ed7f525b5fb719a9c5b7ccf7cc01fae0310822)

> thank you

❤️

<sub>(BTW idk if this is a coincidence but 1 day ago i commented on this video [here](https://www.youtube.com/watch?v=vF0zqCkbsEU&lc=UgxfR3pA1_aPK2qXw8Z4AaABAg))</sub>
