### ISSUE TITLE
Library unusable 

### ISSUE THREAD

**Issue by expeon07** [GiorgosXou/NeuralNetworks#9]
`#define LOVE \n❤ 𝖀𝖓𝖈𝖔𝖓𝖉𝖎𝖙𝖎𝖔𝖓𝖆𝖑 𝕷𝖔𝖛𝖊 ❤`
in NeuralNetwork.h

**Comment by expeon07** [comment]
Created a pull request commenting out the errors.

**Comment by GiorgosXou** [comment]
https://github.com/GiorgosXou/NeuralNetworks/pull/10
